{% set name = "asimov-gwdata" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3dce6f9c242880022e3a75cf754b860ce9685e31025778cca53a1faee1875ce5

build:
  entry_points:
    - gwdata = datafind.main:get_data
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >=3.7
    - gwosc
    - asimov >=0.4.0
    - pesummary

test:
  imports:
    - datafind
  commands:
    - pip check
    - cd tests && bash asimov-test-script.sh
  requires:
    - pip

about:
  home: https://git.ligo.org/asimov/pipelines/gwdata
  summary: An asimov plugin to make downloading gravitational wave data easier
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - transientlunatic
    - mj-will
